apiVersion: v1
kind: Namespace
metadata:
  name: user-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: order-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend 