apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: frontend-base

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: frontend
  app.kubernetes.io/name: frontend
  app.kubernetes.io/part-of: gitops-learning

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1" 