version: '3.8'

networks:
  micro_network:
    name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: ./user-service
    ports:
    - "5001:5001"
    environment:
      - CONFIGURATION_SETUP=config.ProductionConfig
      # External database connection
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASSWORD=D$bP@ssW0rd
      - DB_NAME=user_management
    networks:
      - micro_network
    restart: always
    # No depends_on for external DB

  product-api:
    container_name: cproduct-service
    build:
      context: ./product-service
    ports:
    - "5002:5002"
    environment:
      - CONFIGURATION_SETUP=config.ProductionConfig
      # External database connection
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASSWORD=D$bP@ssW0rd
      - DB_NAME=product_catalog
    networks:
      - micro_network
    restart: always

  order-api:
    container_name: corder-service
    build:
      context: ./order-service
    ports:
    - "5003:5003"
    environment:
      - CONFIGURATION_SETUP=config.ProductionConfig
      # External database connection
      - DB_HOST=your-rds-endpoint.amazonaws.com
      - DB_PORT=3306
      - DB_USER=dbuser
      - DB_PASSWORD=D$bP@ssW0rd
      - DB_NAME=order_management
    networks:
      - micro_network
    restart: always

  frontend-app:
    container_name: cfrontend-app
    build:
      context: ./frontend
    ports:
    - "8080:5000"
    environment:
      - CONFIGURATION_SETUP=config.ProductionConfig
    networks:
      - micro_network
    restart: always 