apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/staging-external-secrets-role
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: external-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        serviceAccount:
          name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-database-secrets
  namespace: external-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-database-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: gitops-learning/database
        property: url
    - secretKey: database-password
      remoteRef:
        key: gitops-learning/database
        property: password