# docker-compose.yml
version: '3.8'

volumes:
  userdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: .
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: mysql:8
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: R00tD$bP@ssW0rd
      MYSQL_DATABASE: user_management
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: D$bP@ssW0rd
    networks:
      - micro_network
    volumes:
    - userdb_vol:/var/lib/mysql