# production-playbook.yml
---
- name: Deploy Production Environment with Docker
  hosts: production
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_compose_version: "2.24.7"

  tasks:
    - name: Clean apt cache and remove lock files
      ansible.builtin.shell: |
        rm -f /var/lib/apt/lists/lock
        rm -f /var/cache/apt/archives/lock
        rm -f /var/lib/dpkg/lock*
        rm -f /var/lib/dpkg/lock-frontend
        rm -f /var/lib/apt/lists/lock-frontend
        dpkg --configure -a || true
      become: yes
      ignore_errors: yes

    - name: Wait for apt to settle
      ansible.builtin.pause:
        seconds: 5

    - name: Update apt cache and install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present
        update_cache: yes
        cache_valid_time: 3600
        lock_timeout: 120
      become: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Add Docker repository (auto OS detection)
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      become: yes

    - name: Install Docker Engine
      ansible.builtin.apt:
        name: docker-ce
        state: present
        lock_timeout: 120
      become: yes

    - name: Install MySQL client
      ansible.builtin.apt:
        name: mysql-client-core-8.0
        state: present
        lock_timeout: 120
      become: yes

    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        lock_timeout: 120
      become: yes

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        timeout: 60
        force: yes
      become: yes

    - name: Ensure ubuntu user exists
      ansible.builtin.user:
        name: ubuntu
        state: present
      become: yes

    - name: Add user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes
      become: yes

    - name: Create production application directory
      ansible.builtin.file:
        path: /home/ubuntu/production-app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become: yes

    - name: Template production docker-compose.yml
      ansible.builtin.template:
        src: files/production-docker-compose.yml.j2
        dest: /home/ubuntu/production-app/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      vars:
        production_ip: "{{ production_ip | default('localhost') }}"
      become: yes

    - name: Create production environment file
      ansible.builtin.template:
        src: files/production.env.j2
        dest: /home/ubuntu/production-app/.env
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      vars:
        production_ip: "{{ production_ip | default('localhost') }}"
      become: yes

    - name: Pull latest Docker images
      ansible.builtin.shell: |
        docker pull 0xsaju/flask-user-service:production
        docker pull 0xsaju/flask-product-service:production
        docker pull 0xsaju/flask-order-service:production
        docker pull 0xsaju/flask-frontend:production
      args:
        chdir: /home/ubuntu/production-app
      become: no

    - name: Start Production Docker Compose stack
      ansible.builtin.shell: |
        /usr/local/bin/docker-compose -f /home/ubuntu/production-app/docker-compose.yml up -d
      args:
        chdir: /home/ubuntu/production-app
      become: no

    - name: Wait for Docker services to start
      ansible.builtin.shell: |
        echo "Waiting for Docker services to initialize..."
        sleep 30
        docker ps
      args:
        chdir: /home/ubuntu/production-app
      register: docker_status
      become: no

    - name: Display Docker status
      ansible.builtin.debug:
        var: docker_status.stdout_lines

    - name: Wait for production frontend to be up
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8080"
        status_code: 200
        timeout: 30
        follow_redirects: all
      register: production_frontend_status
      retries: 6
      delay: 10
      until: production_frontend_status.status == 200
      ignore_errors: yes

    - name: Wait for production user service to be up
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5001/api/users"
        status_code: 200
        timeout: 30
      register: production_user_status
      retries: 6
      delay: 10
      until: production_user_status.status == 200
      ignore_errors: yes

    - name: Wait for production product service to be up
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5002/api/products"
        status_code: 200
        timeout: 30
      register: production_product_status
      retries: 6
      delay: 10
      until: production_product_status.status == 200
      ignore_errors: yes

    - name: Wait for production order service to be up
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5003/api/orders"
        status_code: 200
        timeout: 30
      register: production_order_status
      retries: 6
      delay: 10
      until: production_order_status.status == 200
      ignore_errors: yes

    - name: Check service status
      ansible.builtin.debug:
        msg: |
          Frontend Status: {{ production_frontend_status.status | default('Not responding') }}
          User Service Status: {{ production_user_status.status | default('Not responding') }}
          Product Service Status: {{ production_product_status.status | default('Not responding') }}
          Order Service Status: {{ production_order_status.status | default('Not responding') }}

    - name: Display production deployment info
      ansible.builtin.debug:
        msg: |
          Production deployment completed successfully!
          Frontend: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8080
          User Service: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5001
          Product Service: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5002
          Order Service: http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:5003