apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: user-service-base

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: user-service
  app.kubernetes.io/name: user-service
  app.kubernetes.io/part-of: gitops-learning

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1" 